### ISSUE TITLE
Parallel processing fails on macOS

### ISSUE THREAD

**Issue by bernardlf** [chris-prener/censusxy#42]
I'm having an issue with parallel processing on macOS, potentially related to changes to CoreFoundation and/or forking in recent macOS updates. When I set parallel = 2 (or any number > 1) I receive the following error:

```r
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column
In addition: Warning messages:
1: In parallel::mclapply(batches, batch_geocoder, return, timeout,  :
  scheduled cores 1, 2 did not deliver results, all values of the jobs will be affected
```

I can reproduce this error on an M1 Mac and Intel Mac, both running macOS 12.4. I didn't have any issues with parallel processing in censusxy circa February 2022.

Reprex below:
```r
library(censusxy)

data <- stl_homicides

## Works
homicide_sf <- cxy_geocode(data, street = "street_address", city = "city", state = "state", output="full", vintage = 'Current_Current', benchmark = "Public_AR_Current", return="geographies", class="dataframe", parallel=1)

## Breaks with 'The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().'
homicide_sf <- cxy_geocode(data, street = "street_address", city = "city", state = "state", output="full", vintage = 'Current_Current', benchmark = "Public_AR_Current", return="geographies", class="dataframe", parallel=2)
```

 - OS: macOS 12.4
 - Version of R: 4.2.0
 - Version of RStudio: 2022.02.2
 - Version of censusxy: 1.0.2.9000 (also failed under CRAN version)
 - Session info:

```r
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] censusxy_1.0.2.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3       magrittr_2.0.3     units_0.8-0        tidyselect_1.1.2   R6_2.5.1           rlang_1.0.2       
 [7] fansi_1.0.3        httr_1.4.3         dplyr_1.0.9        tools_4.2.0        parallel_4.2.0     grid_4.2.0        
[13] KernSmooth_2.23-20 utf8_1.2.2         cli_3.3.0          e1071_1.7-9        DBI_1.1.2          ellipsis_0.3.2    
[19] class_7.3-20       assertthat_0.2.1   tibble_3.1.7       lifecycle_1.0.1    sf_1.0-7           crayon_1.5.1      
[25] purrr_0.3.4        vctrs_0.4.1        curl_4.3.2         mime_0.12          glue_1.6.2         proxy_0.4-26      
[31] compiler_4.2.0     pillar_1.7.0       generics_0.1.2     classInt_0.4-3     pkgconfig_2.0.3
```

**Comment by bernardlf** [comment]
Here is the error when this is run via Terminal:

```r
objc[6659]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[6659]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**Comment by chris-prener** [comment]
thanks for submitting this - the issue appears to be with forked parallel processes on macOS. will continue investigating!

**Comment by chris-prener** [comment]
quick update - had to update to macOS 12.4 but can replicate the issue. This is beyond `censusxy` - it has to do with how `parallels::mclapply()` function interfaces with the operating system. Unfortunately, since `parallels` is part of R core, it won't be patched as quickly I don't think. Will keep this open for now, but we'll need to explore whether this feature can be either changed to another function within `parallels` or whether we need to temporarily discontinue supporting parallel processing on UNIX machines.

**Comment by chris-prener** [comment]
In addition to updating our documentation, we now return a specific error when this occurs that points users to the wesbite. I have also noticed that it is possible to restart your R session and get the code to execute correctly.

**Comment by chris-prener** [comment]
OK @bernardlf - thanks for your patience - I've patched the Github version of the package to address this issue and am no longer getting errors on my local 12.4 install of macOS. Can you test the `remotes::install_github("slu-openGIS/censusxy")` version of the package out? Thanks!

**Comment by bernardlf** [comment]
I'm not getting errors anymore either, and parallel processing appears to be working. Thanks for addressing this @chris-prener!

**Comment by chris-prener** [comment]
My pleasure! Thanks for using the package!
